# ================================================
# AzureAuth - РљРѕРЅС„РёРіСѓСЂР°С†РёСЏ РїР»Р°РіРёРЅР° Р°РІС‚РѕСЂРёР·Р°С†РёРё
# Р Р°Р·СЂР°Р±РѕС‚Р°РЅРѕ РґР»СЏ СЃРµСЂРІРµСЂР° AzureMyst
# ================================================

# РќР°СЃС‚СЂРѕР№РєРё Р±Р°Р·С‹ РґР°РЅРЅС‹С…
database:
  # РўРёРї Р±Р°Р·С‹ РґР°РЅРЅС‹С…: SQLITE РёР»Рё MYSQL
  type: SQLITE
  
  # РџСЂРµС„РёРєСЃ С‚Р°Р±Р»РёС† РІ Р±Р°Р·Рµ РґР°РЅРЅС‹С…
  table-prefix: "azureauth_"
  
  # РќР°СЃС‚СЂРѕР№РєРё MySQL (РёСЃРїРѕР»СЊР·СѓСЋС‚СЃСЏ С‚РѕР»СЊРєРѕ РїСЂРё type: MYSQL)
  mysql:
    host: "localhost"
    port: 3306
    database: "azureauth"
    username: "root"
    password: "password"
    
    # РџР°СЂР°РјРµС‚СЂС‹ РїРѕРґРєР»СЋС‡РµРЅРёСЏ
    connection-properties:
      useSSL: false
      useUnicode: true
      characterEncoding: "UTF-8"
      autoReconnect: true
      maxReconnects: 3

# РћСЃРЅРѕРІРЅС‹Рµ РЅР°СЃС‚СЂРѕР№РєРё Р°РІС‚РѕСЂРёР·Р°С†РёРё
auth:
  # Р’РєР»СЋС‡РёС‚СЊ СЂРµРіРёСЃС‚СЂР°С†РёСЋ РЅРѕРІС‹С… РёРіСЂРѕРєРѕРІ
  registration-enabled: true
  
  # РњРёРЅРёРјР°Р»СЊРЅР°СЏ РґР»РёРЅР° РїР°СЂРѕР»СЏ
  min-password-length: 6
  
  # РњР°РєСЃРёРјР°Р»СЊРЅР°СЏ РґР»РёРЅР° РїР°СЂРѕР»СЏ
  max-password-length: 32
  
  # Р’СЂРµРјСЏ РЅР° Р°РІС‚РѕСЂРёР·Р°С†РёСЋ (РІ СЃРµРєСѓРЅРґР°С…)
  login-timeout: 60
  
  # РњР°РєСЃРёРјР°Р»СЊРЅРѕРµ РєРѕР»РёС‡РµСЃС‚РІРѕ РїРѕРїС‹С‚РѕРє РІС…РѕРґР°
  max-login-attempts: 3
  
  # РќР°СЃС‚СЂРѕР№РєРё СЃРµСЃСЃРёР№
  sessions:
    # Р’РєР»СЋС‡РёС‚СЊ СЃРёСЃС‚РµРјСѓ СЃРµСЃСЃРёР№ (Р·Р°РїРѕРјРёРЅР°РЅРёРµ IP)
    enabled: true
    
    # Р”Р»РёС‚РµР»СЊРЅРѕСЃС‚СЊ СЃРµСЃСЃРёРё РІ СЃРµРєСѓРЅРґР°С… (3600 = 1 С‡Р°СЃ)
    duration: 3600
    
    # РђРІС‚РѕРјР°С‚РёС‡РµСЃРєРё СЃРѕР·РґР°РІР°С‚СЊ СЃРµСЃСЃРёСЋ РїСЂРё РІС…РѕРґРµ
    auto-create: true
  
  # РќР°СЃС‚СЂРѕР№РєРё РєР°РїС‡Рё
  captcha:
    # Р’РєР»СЋС‡РёС‚СЊ РєР°РїС‡Сѓ РїРѕСЃР»Рµ РЅРµСѓРґР°С‡РЅС‹С… РїРѕРїС‹С‚РѕРє
    enabled: true
    
    # РџРѕРєР°Р·С‹РІР°С‚СЊ РєР°РїС‡Сѓ РїРѕСЃР»Рµ N РЅРµСѓРґР°С‡РЅС‹С… РїРѕРїС‹С‚РѕРє
    after-attempts: 2
    
    # Р”Р»РёРЅР° РєРѕРґР° РєР°РїС‡Рё
    code-length: 6

# РќР°СЃС‚СЂРѕР№РєРё Р±РµР·РѕРїР°СЃРЅРѕСЃС‚Рё
security:
  # РџСЂРёРЅСѓР¶РґР°С‚СЊ Рє РёСЃРїРѕР»СЊР·РѕРІР°РЅРёСЋ СЃР»РѕР¶РЅС‹С… РїР°СЂРѕР»РµР№
  force-secure-password: true
  
  # Р‘РµР»С‹Р№ СЃРїРёСЃРѕРє IP-Р°РґСЂРµСЃРѕРІ
  ip-whitelist:
    enabled: false
    # РЎРїРёСЃРѕРє СЂР°Р·СЂРµС€РµРЅРЅС‹С… IP (РµСЃР»Рё enabled: true)
    allowed-ips:
      - "127.0.0.1"
      - "192.168.1.0/24"
  
  # РџСЂРѕРІРµСЂРєР° email (С‚СЂРµР±СѓРµС‚ РґРѕРїРѕР»РЅРёС‚РµР»СЊРЅРѕР№ РЅР°СЃС‚СЂРѕР№РєРё)
  email-verification:
    enabled: false
    
  # Р’СЂРµРјСЏ Р±Р»РѕРєРёСЂРѕРІРєРё РїРѕСЃР»Рµ РїСЂРµРІС‹С€РµРЅРёСЏ Р»РёРјРёС‚Р° РїРѕРїС‹С‚РѕРє (РІ СЃРµРєСѓРЅРґР°С…)
  brute-force-protection-time: 300
  
  # РџСЂРѕРІРµСЂРєР° РЅР° Р±РѕС‚-Р°РєС‚РёРІРЅРѕСЃС‚СЊ
  anti-bot:
    enabled: true
    # РњРёРЅРёРјР°Р»СЊРЅРѕРµ РІСЂРµРјСЏ РјРµР¶РґСѓ РїРѕРїС‹С‚РєР°РјРё РІС…РѕРґР° (РјСЃ)
    min-login-interval: 1000

# РћРіСЂР°РЅРёС‡РµРЅРёСЏ РґР»СЏ РЅРµР°РІС‚РѕСЂРёР·РѕРІР°РЅРЅС‹С… РёРіСЂРѕРєРѕРІ
restrictions:
  # Р‘Р»РѕРєРёСЂРѕРІР°С‚СЊ С‡Р°С‚
  block-chat: true
  
  # Р‘Р»РѕРєРёСЂРѕРІР°С‚СЊ РґРІРёР¶РµРЅРёРµ
  block-movement: true
  
  # Р‘Р»РѕРєРёСЂРѕРІР°С‚СЊ РєРѕРјР°РЅРґС‹ (РєСЂРѕРјРµ /login, /register)
  block-commands: true
  
  # Р‘Р»РѕРєРёСЂРѕРІР°С‚СЊ РІР·Р°РёРјРѕРґРµР№СЃС‚РІРёРµ СЃ РёРЅРІРµРЅС‚Р°СЂРµРј
  block-inventory: true
  
  # Р‘Р»РѕРєРёСЂРѕРІР°С‚СЊ РІР·Р°РёРјРѕРґРµР№СЃС‚РІРёРµ СЃ Р±Р»РѕРєР°РјРё
  block-interactions: true
  
  # Р‘Р»РѕРєРёСЂРѕРІР°С‚СЊ РїРѕР»СѓС‡РµРЅРёРµ СѓСЂРѕРЅР°
  block-damage: false
  
  # Р Р°Р·СЂРµС€РµРЅРЅС‹Рµ РєРѕРјР°РЅРґС‹ РґР»СЏ РЅРµР°РІС‚РѕСЂРёР·РѕРІР°РЅРЅС‹С… РёРіСЂРѕРєРѕРІ
  allowed-commands:
    - "login"
    - "l"
    - "РІРѕР№С‚Рё"
    - "register"
    - "reg"
    - "СЂРµРіРёСЃС‚СЂР°С†РёСЏ"
    - "help"
    - "?"

# РќР°СЃС‚СЂРѕР№РєРё СѓРІРµРґРѕРјР»РµРЅРёР№
notifications:
  # РџРѕР»РѕСЃР° Р±РѕСЃСЃР° (Boss Bar)
  bossbar:
    enabled: true
    color: "RED"
    style: "PROGRESS"
    
  # РЎС‚СЂРѕРєР° РґРµР№СЃС‚РІРёР№ (Action Bar)
  actionbar:
    enabled: true
    update-interval: 20 # С‚РёРєРё (20 С‚РёРєРѕРІ = 1 СЃРµРєСѓРЅРґР°)
    
  # Р—Р°РіРѕР»РѕРІРєРё (Title)
  title:
    enabled: true
    fade-in: 10
    stay: 70
    fade-out: 20
    
  # Р—РІСѓРєРѕРІС‹Рµ СЌС„С„РµРєС‚С‹
  sound:
    enabled: true
    success: "ENTITY_PLAYER_LEVELUP"
    error: "ENTITY_VILLAGER_NO"
    warning: "BLOCK_NOTE_BLOCK_PLING"

# РќР°СЃС‚СЂРѕР№РєРё СЃРѕРѕР±С‰РµРЅРёР№
messages:
  # РЇР·С‹Рє РїРѕ СѓРјРѕР»С‡Р°РЅРёСЋ
  language: "ru"
  
  # РџСЂРµС„РёРєСЃ СЃРѕРѕР±С‰РµРЅРёР№
  prefix: "&6[&bAzure&3Auth&6]"
  
  # РџРѕРєР°Р·С‹РІР°С‚СЊ РїСЂРµС„РёРєСЃ РІ СЃРѕРѕР±С‰РµРЅРёСЏС…
  show-prefix: true

# РќР°СЃС‚СЂРѕР№РєРё Р»РѕРіРёСЂРѕРІР°РЅРёСЏ
logging:
  # Р’РєР»СЋС‡РёС‚СЊ Р»РѕРіРёСЂРѕРІР°РЅРёРµ
  enabled: true
  
  # Р›РѕРіРёСЂРѕРІР°С‚СЊ РІ С„Р°Р№Р»
  log-to-file: true
  
  # Р›РѕРіРёСЂРѕРІР°С‚СЊ РІ РєРѕРЅСЃРѕР»СЊ
  log-to-console: true
  
  # Р›РѕРіРёСЂРѕРІР°С‚СЊ РїРѕРїС‹С‚РєРё РІС…РѕРґР°
  log-login-attempts: true
  
  # Р›РѕРіРёСЂРѕРІР°С‚СЊ СЂРµРіРёСЃС‚СЂР°С†РёРё
  log-registrations: true
  
  # Р›РѕРіРёСЂРѕРІР°С‚СЊ СЃРјРµРЅСѓ РїР°СЂРѕР»РµР№
  log-password-changes: true
  
  # Р›РѕРіРёСЂРѕРІР°С‚СЊ РїРѕРґРѕР·СЂРёС‚РµР»СЊРЅСѓСЋ Р°РєС‚РёРІРЅРѕСЃС‚СЊ
  log-suspicious-activity: true

# РРЅС‚РµРіСЂР°С†РёРё СЃ РґСЂСѓРіРёРјРё РїР»Р°РіРёРЅР°РјРё
integrations:
  # PlaceholderAPI
  placeholderapi:
    enabled: true
    
  # LuckPerms
  luckperms:
    enabled: true
    # РђРІС‚РѕРјР°С‚РёС‡РµСЃРєРё РІС‹РґР°РІР°С‚СЊ РіСЂСѓРїРїСѓ РїРѕСЃР»Рµ СЂРµРіРёСЃС‚СЂР°С†РёРё
    auto-assign-group: "obychnyy-zhitel"
    
  # Vault (РґР»СЏ СЌРєРѕРЅРѕРјРёРєРё)
  vault:
    enabled: true
    # РЎС‚РѕРёРјРѕСЃС‚СЊ СЂРµРіРёСЃС‚СЂР°С†РёРё (0 = Р±РµСЃРїР»Р°С‚РЅРѕ)
    registration-cost: 0.0

# РќР°СЃС‚СЂРѕР№РєРё РїСЂРѕРёР·РІРѕРґРёС‚РµР»СЊРЅРѕСЃС‚Рё
performance:
  # РСЃРїРѕР»СЊР·РѕРІР°С‚СЊ Р°СЃРёРЅС…СЂРѕРЅРЅС‹Рµ РѕРїРµСЂР°С†РёРё СЃ Р‘Р”
  async-database: true
  
  # РљСЌС€РёСЂРѕРІР°РЅРёРµ РґР°РЅРЅС‹С… Р°РІС‚РѕСЂРёР·Р°С†РёРё
  cache:
    enabled: true
    # Р Р°Р·РјРµСЂ РєСЌС€Р°
    size: 1000
    # Р’СЂРµРјСЏ Р¶РёР·РЅРё Р·Р°РїРёСЃРё РІ РєСЌС€Рµ (СЃРµРєСѓРЅРґС‹)
    expire-after: 300
    
  # РђРІС‚РѕРјР°С‚РёС‡РµСЃРєР°СЏ РѕС‡РёСЃС‚РєР° СѓСЃС‚Р°СЂРµРІС€РёС… РґР°РЅРЅС‹С…
  cleanup:
    enabled: true
    # РРЅС‚РµСЂРІР°Р» РѕС‡РёСЃС‚РєРё (СЃРµРєСѓРЅРґС‹)
    interval: 3600
    # РЈРґР°Р»СЏС‚СЊ СЃРµСЃСЃРёРё СЃС‚Р°СЂС€Рµ N РґРЅРµР№
    max-session-age-days: 30

# Р”РѕРїРѕР»РЅРёС‚РµР»СЊРЅС‹Рµ РЅР°СЃС‚СЂРѕР№РєРё
advanced:
  # РСЃРїРѕР»СЊР·РѕРІР°С‚СЊ UUID РёР»Рё РёРјСЏ РґР»СЏ РёРґРµРЅС‚РёС„РёРєР°С†РёРё
  use-uuid: true
  
  # РџСЂРёРЅСѓР¶РґР°С‚СЊ Рє СЃРјРµРЅРµ РЅРёРєР° РїСЂРё РїРµСЂРІРѕРј РІС…РѕРґРµ
  force-name-change: false
  
  # РњР°РєСЃРёРјР°Р»СЊРЅРѕРµ РєРѕР»РёС‡РµСЃС‚РІРѕ Р°РєРєР°СѓРЅС‚РѕРІ СЃ РѕРґРЅРѕРіРѕ IP
  max-accounts-per-ip: 3
  
  # РџСЂРѕРІРµСЂСЏС‚СЊ РІРµСЂСЃРёСЋ РєР»РёРµРЅС‚Р°
  version-check:
    enabled: false
    min-version: "1.20.0"
    max-version: "1.21.4"

# Р РµР¶РёРј РѕС‚Р»Р°РґРєРё (РЅРµ СЂРµРєРѕРјРµРЅРґСѓРµС‚СЃСЏ РЅР° РїСЂРѕРґР°РєС€РµРЅРµ)
debug:
  enabled: false
  log-queries: false
  log-cache-operations: false
